### ISSUE TITLE
outputFile relative to project root rather than karma basePath

### ISSUE THREAD

**Issue by dominictobias** [Nemesarial/karma-dhtml-reporter#4]
Hi, thanks for the plugin. My `basePath` is set to `app/assets/js` - seems to me it would be nice to set the `outputFile` to something in the project route if possible, but specifying an absolute path, or a relative back path like ../../ results in a `Error: ENOENT, open..` access error.

**Comment by mholtzhausen** [comment]
Hi Dominic. It is relative to the Karma basePath in the karma config. The script does not have access to your project base path, so it cannot set it relative to that. I have not tried it, but I think using `/../../something` should work. The code responsible for determining the path of the output file looks like this:
    var outFile=basePath+options.outputFile;

I think yours may fail because your basePath + the example route you gave does not add up to a valid route: `app/assets/js`+`../..` is not valid

I will add better path concatenation support when I have the time.
